FROM openjdk:11

# Add Maintainer Info
LABEL maintainer="bcesarmotta@yahoo.com.br"

# Add a volume pointing to /tmp
VOLUME /tmp

# Make port 8761 available to the world outside this container
EXPOSE 8761

# The application's jar file
ARG JAR_FILE=target/*.jar

ADD ${JAR_FILE} service-discovery.jar

# Run the jar file 
ENTRYPOINT ["java",/service-discovery.jar"-jar","/websocket-demo.jar"]
