version: '3.4'
services:
  common:
    restart: always
    build:
      network: host
      context: ./commons/
      dockerfile: Dockerfile
    expose:
      - 8081
    ports:
      - "80:80"
      - 8081:8081
    network_mode: host
    tty: true

  mongodb:
    container_name: mongo
    image: mongo:latest
    restart: always
    expose:
      - 27017
    ports:
      - 27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin123
    network_mode: host
    tty: true

  activeMQ:
    container_name: activeMQ
    image: rmohr/activemq
    restart: always
    network_mode: host
    tty: true

  gateway-service:
    build:
      network: host
      context: ./gateway
      dockerfile: Dockerfile
    restart: on-failure
    volumes:
      - /data/gateway-service
    expose:
      - 8111
    ports:
      - 8111
    tty: true
    network_mode: host

  discovery-service:
    build:
      network: host
      context: ./discovery-server
      dockerfile: Dockerfile
    restart: on-failure
    volumes:
      - /data/discovery-server
    expose:
      - 8761
    ports:
      - 8761
    tty: true
    network_mode: host

  football-team:
    build:
      network: host
      context: ./football-team
      dockerfile: Dockerfile
    restart: on-failure
    expose:
      - 8084
      - 8081
    ports:
      - "80:80"
    tty: true
    network_mode: host
    depends_on:
      - common
      - mongodb
      - discovery-service
      - gateway-service

  supporter-member:
    build:
      network: host
      context: ./supporter-member
      dockerfile: Dockerfile
    restart: on-failure
    expose:
      - 8085
      - 8081
    ports:
      - "80:80"
    tty: true
    network_mode: host
    depends_on:
      - common
      - mongodb
      - discovery-service
      - gateway-service

  campaign-service:
    build:
      network: host
      context: ./campaign
      dockerfile: Dockerfile
    restart: on-failure
    expose:
      - 8083
      - 8081
    ports:
      - "80:80"
    tty: true
    network_mode: host
    depends_on:
      - common
      - mongodb
      - discovery-service
      - gateway-service