version: '3.4'
services:
  common:
    network_mode: host
    build:
      network: host
      context: ./commons/
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "80:80"
    tty: true

  mongodb:
    container_name: mongo
    image: mongo:latest
    restart: always
    expose:
      - 27017
    ports:
      - 27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin123
    network_mode: host
    tty: true

  activeMQ:
    container_name: activeMQ
    image: rmohr/activemq
    restart: always
    network_mode: host
    tty: true

  discovery-service:
    build:
      context: ./discovery-server
      dockerfile: Dockerfile
    restart: on-failure
    volumes:
      - /data/discovery-server
    expose:
      - 8761
    ports:
      - 8761
    tty: true
    network_mode: host

  football-team:
    build:
      context: ./football-team
      dockerfile: Dockerfile
    restart: on-failure
    volumes:
      - /data/football-team
    expose:
      - 8084
    ports:
      - 8084
    tty: true
    network_mode: host
    depends_on:
      - common
      - mongodb
      - discovery-service
  campaign:
    build:
      context: ./campaign
      dockerfile: Dockerfile
    restart: on-failure
    volumes:
      - /data/campaign
    expose:
      - 8083
    ports:
      - 8083
    tty: true
    network_mode: host
    depends_on:
      - common
      - mongodb
      - discovery-service

  supporter-member:
    build:
      context: ./supporter-member
      dockerfile: Dockerfile
    restart: on-failure
    volumes:
      - /data/supporter-member
    expose:
      - 8085
    ports:
      - 8085
    tty: true
    network_mode: host
    depends_on:
      - common
      - mongodb
      - discovery-service

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    restart: on-failure
    volumes:
      - /data/gateway
    expose:
      - 8111
    ports:
      - 8111
    tty: true
    network_mode: host