server:
  port: 8111
spring:
  application:
    name: zuulserver

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

zuul:
  routes:
    campaigns:
      path: /campaign/**
      url: http://localhost:8083/campaign/

    supporter-member:
      path: /supporter-member/**
      url: http://localhost:8085/supporter-member/

    football-team:
      path: /football-team/**
      url: http://localhost:8084/football-team/