server:
  port: 8083
spring:
  application:
    name: CAMPAIGN_SERVICE
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      username: admin
      password: admin123
      database: microservices
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      # defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  instance:
    preferIpAddress: true