server:
  port: 8085
spring:
  application:
    name: SUPPORTER_MEMBER_SERVICE
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      username: admin
      password: admin123
      database: microservices
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true